'use client';
import React from 'react';
import { useProjectStore } from '@/store/projectStore';
import { runFullCalculation } from '@/lib/calculations';

export default function ReportPanel() {
  const { project, activeScenarioId } = useProjectStore();
  const scenario = project?.scenarios.find(s => s.id === activeScenarioId);
  const results = scenario?.results;

  const formatN = (n: number | undefined, d = 1) => n !== undefined && isFinite(n) ? n.toFixed(d) : '—';

  const generateCSV = () => {
    if (!results) return;
    const rows = [['Distance (m)', 'Radiation (kW/m²)', 'Noise (dBA)']];
    const len = Math.min(results.radiation.distances.length, results.noise.distances.length);
    for (let i = 0; i < len; i++) {
      rows.push([results.radiation.distances[i].toString(), results.radiation.intensities[i].toFixed(3), results.noise.splValues[i].toFixed(1)]);
    }
    const csv = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project?.name || 'report'}-data.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generatePDFContent = () => {
    if (!project || !scenario || !results) return;
    const content = `
FLARE RADIATION, NOISE & SAFETY RADIUS REPORT
==============================================

Project: ${project.name}
Location: ${project.location}
Client: ${project.client}
Date: ${new Date().toLocaleDateString()}

SCENARIO: ${scenario.name}
==============================================

INPUT DATA
----------
Flow Rate: ${scenario.flowRate} kg/hr
Stack Height: ${scenario.stackHeight} m
Wind Speed: ${scenario.windSpeed} m/s
Fraction Radiated: ${scenario.fractionRadiated}
Combustion Efficiency: ${(scenario.combustionEfficiency * 100).toFixed(0)}%

CALCULATED RESULTS
------------------
Heat Release: ${formatN(results.radiation.heatRelease / 1000, 0)} MW
Flame Length: ${formatN(results.radiation.flameLength)} m
Flame Tilt: ${formatN(results.radiation.flameTilt)}°
Tip Diameter: ${formatN(results.radiation.tipDiameter, 3)} m
Gas Velocity at Tip: ${formatN(results.radiation.gasVelocity)} m/s

SAFE RADII
----------
Exclusion Zone (6.3 kW/m²): ${formatN(results.radiation.safeRadii.equipment_6_3)} m
Restricted Zone (4.7 kW/m²): ${formatN(results.radiation.safeRadii.escape_4_7)} m
Controlled Zone (1.6 kW/m²): ${formatN(results.radiation.safeRadii.personnel_1_6)} m
Property Boundary (3.2 kW/m²): ${formatN(results.radiation.safeRadii.boundary_3_2)} m

Noise Residential (55 dBA): ${formatN(results.noise.safeRadii.residential_55)} m
Noise Industrial (85 dBA): ${formatN(results.noise.safeRadii.industrial_85)} m

OVERALL SAFE RADIUS: ${formatN(results.safeRadiusSummary.overallSafeRadius)} m

COMPLIANCE
----------
${results.safeRadiusSummary.complianceChecks.map(c => `[${c.compliant ? 'PASS' : 'FAIL'}] ${c.standard} - ${c.requirement}`).join('\n')}

---
Generated by Flare Radiation & Safety Software
Standards: API 521, ISO 9613
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.name}-report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!results) {
    return (
      <div className="flex-1 flex items-center justify-center text-gray-500 dark:text-gray-400">
        <div className="text-center">
          <div className="text-4xl mb-3">📄</div>
          <p>Run calculations first to generate reports.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 space-y-4">
      <h2 className="text-lg font-bold dark:text-white">Report Generation</h2>
      <div className="flex gap-3">
        <button onClick={generatePDFContent} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
          📄 Download Report (TXT)
        </button>
        <button onClick={generateCSV} className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700">
          📊 Export Data (CSV)
        </button>
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-4">
        <h3 className="font-semibold dark:text-white mb-2">Report Preview</h3>
        <pre className="text-xs bg-gray-50 dark:bg-gray-900 p-4 rounded overflow-x-auto dark:text-gray-300 whitespace-pre-wrap">
{`FLARE RADIATION, NOISE & SAFETY RADIUS REPORT
==============================================

Project: ${project?.name}
Location: ${project?.location}
Client: ${project?.client}
Date: ${new Date().toLocaleDateString()}

Scenario: ${scenario?.name}

HEAT RELEASE: ${formatN(results.radiation.heatRelease / 1000, 0)} MW
FLAME LENGTH: ${formatN(results.radiation.flameLength)} m
FLAME TILT: ${formatN(results.radiation.flameTilt)}°

SAFE RADII:
  Exclusion (6.3 kW/m²): ${formatN(results.radiation.safeRadii.equipment_6_3)} m
  Restricted (4.7 kW/m²): ${formatN(results.radiation.safeRadii.escape_4_7)} m
  Controlled (1.6 kW/m²): ${formatN(results.radiation.safeRadii.personnel_1_6)} m
  Noise Residential: ${formatN(results.noise.safeRadii.residential_55)} m
  Noise Industrial: ${formatN(results.noise.safeRadii.industrial_85)} m

OVERALL SAFE RADIUS: ${formatN(results.safeRadiusSummary.overallSafeRadius)} m`}
        </pre>
      </div>
    </div>
  );
}
